<a href="https://colab.research.google.com/github/SantiagoBaezaRuffino/THC/blob/main/THC_BaezaRuffinioSantiago_Clase20231024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Ejemplos vistos en clase**

##**Slicing**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:4])
print(arr[1:6])
print(arr[5:6])
print(arr[1:])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[-1])
print(arr[-7:])

[1 2 3 4]
[2 3 4 5 6]
[6]
[2 3 4 5 6 7]
[5 6 7]
[1 2 3 4]
[5 6]
7
[1 2 3 4 5 6 7]


##**Paso**

In [ ]:
print(arr[1:5:2])#la tercer entrada es para dar la orden del paso
print(arr[::2])#imprime todos al paso de dos
print(arr[::3])
print(arr[:4:2])
print(arr[0::1])
print(arr[:0])

[2 4]
[1 3 5 7]
[1 4 7]
[1 3]
[1 2 3 4 5 6 7]
[]


In [ ]:
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr[1, 1:2])
print(arr[1,::])

[7]
[6 7 8 9]


In [ ]:
print(arr[0:2,2])#los indices de las columnas funcionan como los indices de las listas
print(arr[0:3,2])
print(arr[0:1,2])
print(arr[0:2,3])
print(arr[0,4])

[3 8]
[ 3  8 13]
[3]
[4 9]
5


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[0::,2])
print(arr[0:3,3])
print(arr[0:2,1:4])
print(arr[0:1,2:6])

[ 3  8 13]
[ 4  9 14]
[[2 3 4]
 [7 8 9]]
[[3 4 5]]


##**Buscar arreglos**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


##**Reshape, linspace, uniform, Randint**

In [ ]:
x=np.array(list(range(1,7)))
print(x)

[1 2 3 4 5 6]


In [ ]:
matriz = x.reshape(2,3)#los numeros se refiere al numero de columnas y rengoles(num renglones, num columnas)
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matriz = x.reshape(3,2)
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x=np.linspace(0,1,3)
x

array([0. , 0.5, 1. ])

In [ ]:
x=np.linspace(0,2,2)
x

array([0., 2.])

In [ ]:
np.random.uniform(0,2,2)

array([1.16172595, 1.17177523])

In [ ]:
np.random.uniform(0,1,6)


array([0.74120123, 0.13979918, 0.436608  , 0.72924952, 0.4482763 ,
       0.16229745])

In [ ]:
np.random.randint(0,10,size=1)

array([9])

In [ ]:
print(f"Numero pi= {np.pi}")

Numero pi= 3.141592653589793


In [ ]:
angulos = np.array([0,np.pi/2,np.pi])
coseno=np.cos(angulos)
print(f"Los cosenos {coseno}")
print(f"De los angulos {angulos}")
#e-## es cero con <15

Los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
De los angulos [0.         1.57079633 3.14159265]


#**Ejercicios de la clase**

##**Operaciones con arreglos**

In [ ]:
#Suma
x = np.array([1,2,3])
y = np.array([4,5,6])
suma=x+y

La división es:[1 2 3]


In [ ]:
#Resta
resta=x-y
print(resta)

[-3 -3 -3]


In [ ]:
#Multiplicación
mult=x*y
print(mult)

[ 4 10 18]


In [ ]:
#División
div=x/y
print(div)

[0.25 0.4  0.5 ]


##**Random Randint**

In [19]:
#Ejercicio en clase
import numpy as np
numero_aleatorio= np.random.randint(0,10,size=1)
respuesta1="Si"
respuesta2="No"
i=0
while True:
  i+=1
  numero =float(input("Inserte un número del 1 al 10: "))
  respuesta=input(f"¿Su número es: {numero_aleatorio}?:")
  if respuesta == respuesta1:
    print("Excelente")
    break
  elif i==10:
    print("Se terminaron los intentos: ")
    break
  if respuesta == respuesta2:
    print("intenta de nuevo")

    continue



  #respuesta=(input())

Inserte un número del 1 al 10: 4
¿Su número es: [1]?:NO
Inserte un número del 1 al 10: 4
¿Su número es: [1]?:No
intenta de nuevo


KeyboardInterrupt: ignored